/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedUploadRouteImport } from './routes/_authenticated/upload'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedIndicatorsIndexRouteImport } from './routes/_authenticated/indicators.index'
import { Route as AuthenticatedIndicatorsIdRouteImport } from './routes/_authenticated/indicators.$id'
import { Route as AuthenticatedAdminIndicatorsRouteImport } from './routes/_authenticated/admin/indicators'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedUploadRoute = AuthenticatedUploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedIndicatorsIndexRoute =
  AuthenticatedIndicatorsIndexRouteImport.update({
    id: '/indicators/',
    path: '/indicators/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedIndicatorsIdRoute =
  AuthenticatedIndicatorsIdRouteImport.update({
    id: '/indicators/$id',
    path: '/indicators/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminIndicatorsRoute =
  AuthenticatedAdminIndicatorsRouteImport.update({
    id: '/admin/indicators',
    path: '/admin/indicators',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/upload': typeof AuthenticatedUploadRoute
  '/admin/indicators': typeof AuthenticatedAdminIndicatorsRoute
  '/indicators/$id': typeof AuthenticatedIndicatorsIdRoute
  '/indicators/': typeof AuthenticatedIndicatorsIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/upload': typeof AuthenticatedUploadRoute
  '/': typeof AuthenticatedIndexRoute
  '/admin/indicators': typeof AuthenticatedAdminIndicatorsRoute
  '/indicators/$id': typeof AuthenticatedIndicatorsIdRoute
  '/indicators': typeof AuthenticatedIndicatorsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/upload': typeof AuthenticatedUploadRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/admin/indicators': typeof AuthenticatedAdminIndicatorsRoute
  '/_authenticated/indicators/$id': typeof AuthenticatedIndicatorsIdRoute
  '/_authenticated/indicators/': typeof AuthenticatedIndicatorsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/dashboard'
    | '/upload'
    | '/admin/indicators'
    | '/indicators/$id'
    | '/indicators/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/signup'
    | '/dashboard'
    | '/upload'
    | '/'
    | '/admin/indicators'
    | '/indicators/$id'
    | '/indicators'
  id:
    | '__root__'
    | '/_authenticated'
    | '/login'
    | '/signup'
    | '/_authenticated/dashboard'
    | '/_authenticated/upload'
    | '/_authenticated/'
    | '/_authenticated/admin/indicators'
    | '/_authenticated/indicators/$id'
    | '/_authenticated/indicators/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/upload': {
      id: '/_authenticated/upload'
      path: '/upload'
      fullPath: '/upload'
      preLoaderRoute: typeof AuthenticatedUploadRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/indicators/': {
      id: '/_authenticated/indicators/'
      path: '/indicators'
      fullPath: '/indicators/'
      preLoaderRoute: typeof AuthenticatedIndicatorsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/indicators/$id': {
      id: '/_authenticated/indicators/$id'
      path: '/indicators/$id'
      fullPath: '/indicators/$id'
      preLoaderRoute: typeof AuthenticatedIndicatorsIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/indicators': {
      id: '/_authenticated/admin/indicators'
      path: '/admin/indicators'
      fullPath: '/admin/indicators'
      preLoaderRoute: typeof AuthenticatedAdminIndicatorsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedUploadRoute: typeof AuthenticatedUploadRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedAdminIndicatorsRoute: typeof AuthenticatedAdminIndicatorsRoute
  AuthenticatedIndicatorsIdRoute: typeof AuthenticatedIndicatorsIdRoute
  AuthenticatedIndicatorsIndexRoute: typeof AuthenticatedIndicatorsIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedUploadRoute: AuthenticatedUploadRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedAdminIndicatorsRoute: AuthenticatedAdminIndicatorsRoute,
  AuthenticatedIndicatorsIdRoute: AuthenticatedIndicatorsIdRoute,
  AuthenticatedIndicatorsIndexRoute: AuthenticatedIndicatorsIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
